### ISSUE TITLE
Installing on Windows without Visual Studio

### ISSUE THREAD

**Issue by kingoftheconnors** [saprykin/plibsys#82]
Greetings! I'm trying to use this library to make a cross-platform networking program using sockets. So far, I cannot install the library.

I am not using Visual Studio, and I never plan to. The wiki only describes using the "make" command after using cmake, which doesn't work on Windows. Calling mingw32-make on any of the vsxproj files or the .sln file returns `Nothing to be done for '________'`

What should I do?

**Comment by saprykin** [comment]
Hi,

Which compiler do you want to use? MinGW?

**Comment by kingoftheconnors** [comment]
Yes. I'm using VSCode, if that helps as well.

**Comment by saprykin** [comment]
Then the steps would be the same as in the build instructions except two moments. First, you need to pass a proper generator name to cmake in order to generate project makefiles, i.e.

cmake -G "MinGW Makefiles"

The rest of cmake parameters are the same.

Afterwards, you build the library with mingw32-make command.

**Comment by kingoftheconnors** [comment]
Oh, ok. Thanks!
